baseurl = "https://example.com/"
title = "Jose Ignacio"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Jose Guzman"
disqusShortname = "XXX"
googleAnalytics = "XXX"
relativeurls = true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Jose Guzman"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Jose Ignacio"
    description = "Data Blog"
    github = "https://github.com/JoseIGuzman"
    linkedin = "www.linkedin.com/in/jose-ignacio-guzman-68038170"
    twitter = "https://twitter.com/joseignacioguz"
    email = "jignacioguz@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
