baseurl = "/"
title = "Data Blog"
author = "Jose Guzman"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Jose Guzman Data Blog"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/JoseIGuzman"
    weight = 2
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jignacioguz"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/joseignacioguz"
    weight = 4

